### ISSUE TITLE
Can't login to Google account with WsaRelease-1.8.32822.0-GAPPS-pico

### ISSUE THREAD

**Issue by GDT1978** [Shra1V32/WSA-GA-Actions#1]
I followed the setup process but I cannot login to my Google Account. I get green login button but nothing happens when I click on it.

**Comment by Shra1V32** [comment]
It works absolutely fine for me, Dk what's with yours.

**Comment by linuxmobile** [comment]
> It works absolutely fine for me, Dk what's with yours.

I run workflow recently, and i can't access too. I've got playstore, and when i go to access... it's stuck there. Doesn't do anything.

**Comment by Shra1V32** [comment]
Has been fixed finally, Sorry I'm not at my hometown for these many day. Credit goes to @Coxxs
